theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 歌手/词曲作者/演员/慈善家

# 对你自己的简洁描述
description: 2008年，发行专辑《The Fame》出道。2009年，个人单曲《Just Dance》《Poker Face》先后取得美国公告牌百强单曲榜冠军。2010年，在第52届格莱美奖中获得了两项奖；被《时代周刊》评为“全球最具影响力百人榜”艺术家组第1名 
# 你的美照地址
logo: /assets/images/雷迪嘎嘎.jpg

# 你的名字
name: Lady GaGa

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: 963353848@qq.com

# 你目前的住址
address: 纽约曼哈顿

# 你毕业院校
school: 纽约大学

# 你的专业
profession: 

# 你的学位
degree: 大学肄业

# 你获得过的证书或奖励
credential:奥斯卡金像奖最佳原创歌曲/格莱美最佳流行歌曲
